from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from datashuttle.configs.config_class import Configs

from datashuttle.utils import rclone, utils

# -----------------------------------------------------------------------------
# Python API
# -----------------------------------------------------------------------------


def ask_user_for_browser(log: bool = True) -> bool:
    """Ask the user if they have access to an internet browser, for Google Drive set up."""
    message = "Are you running datashuttle on a machine with access to a web browser? (y/n): "
    input_ = utils.get_user_input(message).lower()

    while input_ not in ["y", "n"]:
        utils.print_message_to_user("Invalid input. Press either 'y' or 'n'.")
        input_ = utils.get_user_input(message).lower()

    answer = input_ == "y"

    if log:
        utils.log(message)
        utils.log(f"User answer: {answer}")

    return answer


def prompt_and_get_config_token(
    cfg: Configs,
    gdrive_client_secret: str | None,
    rclone_config_name: str,
    log: bool = True,
) -> str:
    """Prompt the user for rclone config token.

    This function presents the rclone's output/message to ask the user to run a command, authenticate
    with google drive and input the `config_token` generated by rclone. The `config_token` is
    then used to complete rclone's config setup for google drive.
    """
    message = rclone.preliminary_setup_gdrive_config_for_without_browser(
        cfg, gdrive_client_secret, rclone_config_name, log=log
    )
    input_ = utils.get_user_input(
        message + "\nEnter the output here: "
    ).strip()

    return input_


def get_client_secret(log: bool = True) -> str:
    """Prompt the user for their Google Drive client secret key."""
    gdrive_client_secret = utils.get_connection_secret_from_user(
        connection_method_name="Google Drive",
        key_name_full="Google Drive client secret",
        key_name_short="secret key",
        log_status=log,
    )

    return gdrive_client_secret.strip()
