base_tunnel:
  eye_fov:
    fov: 100
    fov_shift: 57
  speed_gain: 1.5
  wall_length: 4.5
  wall_model: walls.egg
  wall_spacing: 9
card:
  position:
  - 0.9
  - 0.9
  size:
  - 0.2
  - 0.2
daqChannel:
  finalV1: Dev1/port1/line0
  finalV2: Dev1/port1/line3
  fiveV: Dev1/port2/line3
  mo1: Dev1/port0/line0
  mo2: Dev1/port2/line6
  odour0: Dev1/port2/line4
  odour1: Dev1/port0/line4
  odour2: Dev1/port1/line7
  odour3: Dev1/port0/line7
  odour4: Dev1/port1/line6
  odour5: Dev1/port0/line2
  odour6: Dev1/port2/line5
  odour7: Dev1/port0/line3
  odour8: Dev1/port1/line4
  odour9: Dev1/port0/line5
  spout1:
    chan: Dev1/ai10
    max_value: 10
    min_value: 0
    threshold: 1
  threeV: Dev1/port1/line1
  threeV2: Dev1/port1/line2
  valve1: Dev2/port0/line1
flip_tunnel:
  continuous_corridor: true
  goals:
  - - 20
    - 36
  - - 74
    - 90
  - - 155
    - 171
  - - 263
    - 279
  io_module: nidaq
  landmarks:
  - - 20
    - 36
  - - 47
    - 63
  - - 74
    - 90
  - - 101
    - 117
  - - 128
    - 144
  - - 155
    - 171
  - - 182
    - 198
  - - 209
    - 225
  - - 236
    - 252
  - - 263
    - 279
  landmarks_sequence:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  length: 288
  manual_reward_with_space: true
  margin_start: 9
  modd1_odours:
  - 1
  - 3
  - 5
  - 7
  - 9
  neutral_texture: grey.png
  odour_diffs:
    flush: 1
    flush_other: 0.75
    flush_same: 1.5
    odour_overlap: 0.05
  reward_distance: 9
  reward_length:
    assist: 0.3
    correct: 0.3
    manual: 0.1
    wrong: 0.3
  reward_prob: 1
  reward_tone_length: 1
  sleep_time: 0
  sound_at_A: true
  sound_dir: examples/sounds/
  sounds:
    0: 6kHz_tone.ogg
  speed_limit: 15
  stimulus_onset: 12
goal_ids:
- 1
- 0
- 2
- 0
- 0
- 3
- 0
- 0
- 0
- 4
inputs:
  speed:
    chan: Dev1/ctr0
    diameter: 0.197
    error_value: 4000000000
    pulses_per_rev: 1000
    threshold: 0.001
logger:
  date_time: '2025-05-16 14:11:49.094411'
  experiment_start_time: '14:11'
  foldername: Z:\public\projects\AtApSuKuSaRe_20250129_HFScohort2\TAA0000066\TrainingData\250516
monitor:
  dual_monitor: true
  monitor1:
    width: 1920
  monitor2:
    height: 1080
    width: 1920
  monitor3:
    height: 1080
    width: 1920
outputs: {}
sequence_task:
  protocol: olfactory_support_l1
  rulename: olfactory_support
walls_sequence:
- random_dots.png
- random_dots.png
- random_dots.png
- logs.png
- logs.png
- random_dots.png
- grating1.jpg
- grating1.jpg
- random_dots.png
- tiles.png
- tiles.png
- random_dots.png
- big_light_rectangles.png
- big_light_rectangles.png
- random_dots.png
- grass.png
- grass.png
- random_dots.png
- big_dark_rectangles.png
- big_dark_rectangles.png
- random_dots.png
- leaves.png
- leaves.png
- random_dots.png
- waves.png
- waves.png
- random_dots.png
- bark.png
- bark.png
- random_dots.png
- big_light_circles.png
- big_light_circles.png
- random_dots.png
